//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public long Id { get; set; }
        public int MinutosToleranciaLlegadaTarde { get; set; }
        public int MinutosToleranciaAusente { get; set; }
        public string HoraEntradaPorDefecto { get; set; }
        public string HoraSalidaPorDefecto { get; set; }
        public string MinutosLactancia { get; set; }
    }
}
