
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AccesoDatos
{

using System;
    using System.Collections.Generic;
    
public partial class Control
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Control()
    {

        this.Perfiles = new HashSet<Perfil>();

    }


    public long Id { get; set; }

    public string Descripcion { get; set; }

    public long FormularioId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Perfil> Perfiles { get; set; }

    public virtual Formulario Formulario { get; set; }

}

}
