//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloBometricoContainer : DbContext
    {
        public ModeloBometricoContainer()
            : base("name=ModeloBometricoContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sector> Sectores { get; set; }
        public virtual DbSet<SubSector> SubSectores { get; set; }
        public virtual DbSet<Agente> Agentes { get; set; }
        public virtual DbSet<Horario> Horarios { get; set; }
        public virtual DbSet<Acceso> Accesos { get; set; }
        public virtual DbSet<Perfil> Perfiles { get; set; }
        public virtual DbSet<Formulario> Formularios { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Control> Controles { get; set; }
        public virtual DbSet<Configuracion> Configuraciones { get; set; }
        public virtual DbSet<TipoNovedad> TipoNovedades { get; set; }
        public virtual DbSet<Novedad> Novedades { get; set; }
        public virtual DbSet<ComisionServicio> ComisionServicios { get; set; }
        public virtual DbSet<Lactancia> Lactancias { get; set; }
    }
}
