
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AccesoDatos
{

using System;
    

public enum TipoAcceso : int
{

    Entrada = 1,

    SalidaParcial = 2,

    EntradaParacial = 3,

    Salida = 4,

}

}
